name: Tests

on:
  push:
    branches:
      - master
      - add/github-actions
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - run: npm install
      - run: npm test
